const state={sessionId:null,revision:0};
const $=id=>document.getElementById(id);
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const body=await response.json();if(!response.ok){const error=new Error(body.detail?.code||`HTTP ${response.status}`);error.status=response.status;error.body=body;throw error}return body}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderContext(payload){const session=payload.session||{};state.sessionId=session.session_id;state.revision=session.revision??0;$("revision").textContent=`revision ${state.revision}`;const active=payload.context?.active?.intent;if(!active){$("scope").className="scope empty";$("scope").textContent="Контекст появится после первого запроса";return}$("scope").className="scope";const periods=(active.periods||[]).map(p=>`${p.date_from}—${p.date_to}`).join(", ")||"—";const operands=(active.operands||[]).map(o=>`<div class="operand"><span class="label">${escapeHtml(o.operand_id)}</span><b>${escapeHtml(o.metric)}</b><div>${(o.entities||[]).map(e=>escapeHtml(e.entity.display_name)).join(" · ")||"без сущностей"}</div></div>`).join("");$("scope").innerHTML=`<div class="chip"><span class="label">Операция</span>${escapeHtml(active.operation)}</div><div class="chip"><span class="label">Период</span>${escapeHtml(periods)}</div>${operands}`}
function addMessage(kind,title,data){const node=document.createElement("article");node.className=`message ${kind}`;node.innerHTML=`<b>${escapeHtml(title)}</b>${data===undefined?"":`<pre>${escapeHtml(typeof data==="string"?data:JSON.stringify(data,null,2))}</pre>`}`;$("messages").append(node);node.scrollIntoView({behavior:"smooth",block:"end"})}
function renderClarification(context){const pending=context?.pending_clarification;if(!pending){$("clarification").hidden=true;return}const question=pending.questions?.[0]||{};$("clarification").hidden=false;$("clarification").innerHTML=`<b>${escapeHtml(question.question||"Уточните параметры")}</b><div>${(question.options||[]).map(option=>`<button type="button" data-answer="${escapeHtml(option)}">${escapeHtml(option)}</button>`).join("")}</div>`;$("clarification").querySelectorAll("button").forEach(button=>button.onclick=()=>send(button.dataset.answer,{answer:button.dataset.answer}))}
async function createSession(){const body=await api("/api/v2/chat/sessions",{method:"POST"});renderContext(body);$("messages").innerHTML="";$("clarification").hidden=true;$("status").textContent="готов"}
async function refresh(){if(!state.sessionId)return;renderContext(await api(`/api/v2/chat/sessions/${encodeURIComponent(state.sessionId)}`))}
async function send(message,clarification=null){addMessage("user","Вы",message);$("status").textContent="выполнение";try{const body=await api("/api/v2/chat",{method:"POST",body:JSON.stringify({session_id:state.sessionId,expected_revision:state.revision,message,execute_db:$("executeDb").checked,clarification})});renderContext(body);renderClarification(body.context);addMessage("system",body.status,body.result);$("status").textContent=body.status}catch(error){if(error.status===409){await refresh();addMessage("system","Контекст обновлён","Другой запрос изменил revision. Повторите отправку.")}else addMessage("system","Ошибка",error.message);$("status").textContent="error"}}
$("chatForm").addEventListener("submit",event=>{event.preventDefault();const message=$("message").value.trim();if(message){$("message").value="";send(message)}});
$("newChat").onclick=createSession;
createSession().catch(error=>{$("status").textContent="backend недоступен";addMessage("system","Не удалось создать сессию",error.message)});
